name: CI

on:
  pull_request: # Runs on PR open/update
    branches:
      - main
  push: # Runs again on merge into main
    branches:
      - main

jobs:
  # ---------------- Linting ----------------
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint + Prettier
        run: npm run lint && npx prettier --check .

  # ---------------- Commitlint ----------------
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check commit messages or PR title
        uses: wagoid/commitlint-github-action@v5
        with:
          configFile: commitlint.config.js

  # ---------------- Tests ----------------
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run frontend tests
        run: npm test

      - name: Run backend tests
        run: cd backend && npm install && npm run test
