name: Enforce Rebase

on:
  pull_request:
    branches: [main]

jobs:
  check-rebase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Check merge base
        id: rebase_check
        run: |
          git fetch origin main
          MERGE_BASE=$(git merge-base HEAD origin/main)
          LATEST_MAIN=$(git rev-parse origin/main)
          echo "MERGE_BASE: $MERGE_BASE"
          echo "LATEST_MAIN: $LATEST_MAIN"

          # Ensure PR branch is directly on top of main
          if [ "$MERGE_BASE" != "$LATEST_MAIN" ]; then
            echo "Branch is not rebased on latest main. Run git fetch, git rebase origin/main and then resolve any/all merge conflicts with the Merge Editor. Continue the rebase with git rebase --continue until your rebase has completed successfully. Finish with git push --force to rebase."
            echo "status=failure" >> $GITHUB_OUTPUT
          else
            echo "status=success" >> $GITHUB_OUTPUT
          fi

      - name: Fail job if rebase check failed
        if: github.event_name == 'pull_request' && steps.rebase_check.outputs.status == 'failure'
        run: exit 1
