name: Ping Discord

on:
  pull_request:
    types: [review_requested]
  pull_request_review:
    types: [submitted]

jobs:
  notify-participants:
    runs-on: ubuntu-latest
    steps:
      - name: Get Discord IDs for reviewer and author
        id: get_discord_ids
        run: |
          USER_MAP='${{ secrets.DISCORD_USER_MAP }}'
          if [[ "${{ github.event_name }}" == "pull_request" && "${{ github.event.action }}" == "review_requested" ]]; then
            REVIEWER="${{ github.event.requested_reviewer.login }}"
          elif [[ "${{ github.event_name }}" == "pull_request_review" ]]; then
            REVIEWER="${{ github.event.review.user.login }}"
          fi
          AUTHOR="${{ github.event.pull_request.user.login }}"
          REVIEWER_ID=$(echo "$USER_MAP" | jq -r --arg user "$REVIEWER" '.[$user]')
          AUTHOR_ID=$(echo "$USER_MAP" | jq -r --arg user "$AUTHOR" '.[$user]')
          echo "reviewer_id=$REVIEWER_ID" >> $GITHUB_OUTPUT
          echo "author_id=$AUTHOR_ID" >> $GITHUB_OUTPUT
        env:
          DISCORD_USER_MAP: ${{ secrets.DISCORD_USER_MAP }}

      - name: Set PR event message
        id: set_message
        run: |
          REVIEWER_ID="${{ steps.get_discord_ids.outputs.reviewer_id }}"
          AUTHOR_ID="${{ steps.get_discord_ids.outputs.author_id }}"
          # Early exit if author is the reviewer for a review event
          if [[ "${{ github.event_name }}" == "pull_request_review" && "$REVIEWER_ID" == "$AUTHOR_ID" ]]; then
            echo "message=" >> $GITHUB_OUTPUT
            exit 0
          fi
          if [[ "${{ github.event_name }}" == "pull_request" && "${{ github.event.action }}" == "review_requested" ]]; then
            echo "message=<@$REVIEWER_ID> you were requested to review [PR #${{ github.event.pull_request.number }}](${{ github.event.pull_request.html_url }}) by <@$AUTHOR_ID>" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "pull_request_review" ]]; then
            case "${{ github.event.review.state }}" in
              approved)
                echo "message=<@$REVIEWER_ID> approved [PR #${{ github.event.pull_request.number }}](${{ github.event.pull_request.html_url }}) by <@$AUTHOR_ID>" >> $GITHUB_OUTPUT
                ;;
              changes_requested)
                echo "message=<@$REVIEWER_ID> requested changes on [PR #${{ github.event.pull_request.number }}](${{ github.event.pull_request.html_url }}) by <@$AUTHOR_ID>" >> $GITHUB_OUTPUT
                ;;
              commented)
                echo "message=<@$REVIEWER_ID> commented on [PR #${{ github.event.pull_request.number }}](${{ github.event.pull_request.html_url }}) by <@$AUTHOR_ID>" >> $GITHUB_OUTPUT
                ;;
            esac
          fi

      - name: Send PR Notifications to Discord
        if: steps.set_message.outputs.message != ''
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: ${{ steps.set_message.outputs.message }}
